plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'tech.kw.android.pandora'
    compileSdk = libs.versions.compileSdk.get().toInteger()

    defaultConfig {
        applicationId "tech.kw.android.pandora"
        minSdk = libs.versions.minSdk.get().toInteger()
        targetSdk = libs.versions.targetSdk.get().toInteger()
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(':pandora-core')

    implementation libs.androidx.appcompat
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.browser
    implementation libs.androidx.lifecycle.process

    implementation libs.androidx.room.runtime
    annotationProcessor libs.androidx.room.compiler

    implementation libs.retrofit.core
    implementation libs.retrofit.converter.gson
    implementation libs.fastjson
}
