plugins {
    alias(libs.plugins.kotlin.jvm)
    id 'maven-publish'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation gradleApi()
    compileOnly libs.android.gradle.plugin
    implementation libs.asm
    implementation libs.asm.commons
    implementation libs.asm.util
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }
}

tasks.withType(Javadoc) {
    options.encoding = "utf-8"
}